# Имя рабочего процесса, отображаемое на GitHub Actions
name: Build and Test Qt Project on Linux (Deep Client Debug)

# События, которые запускают этот рабочий процесс
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Определяем задачи (jobs)
jobs:
  build_linux:
    runs-on: ubuntu-latest # Запускаем на стандартной машине GitHub Actions
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Verify Working Directory and Contents (Pre-build)
      run: |
        echo "Current working directory:"
        pwd
        echo "Contents of jsonclient/ directory:"
        ls -F jsonclient/ # Проверяем содержимое только jsonclient
        echo "--- End of directory listing ---"

    - name: Install Build Essentials and Dependencies
      run: |
        echo "Updating apt packages..."
        sudo apt update -y
        echo "Installing build essentials and other core libraries..."
        sudo apt install -y build-essential libgl1-mesa-dev python3 python3-pip

    - name: Install Qt using aqtinstall
      run: |
        echo "Installing aqtinstall..."
        pip3 install aqtinstall

        echo "Installing Qt 5.15.2 for linux/gcc_64..."
        aqt install-qt linux desktop 5.15.2 gcc_64 --outputdir "$RUNNER_TEMP/Qt"

        echo "QT_PATH=$RUNNER_TEMP/Qt/5.15.2/gcc_64" >> $GITHUB_ENV
        echo "PATH=$RUNNER_TEMP/Qt/5.15.2/gcc_64/bin:$PATH" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$RUNNER_TEMP/Qt/5.15.2/gcc_64/lib" >> $GITHUB_ENV

        echo "PATH (after setting in GITHUB_ENV): $PATH"
        echo "LD_LIBRARY_PATH (after setting in GITHUB_ENV): $LD_LIBRARY_PATH"

    - name: Configure Qt Projects
      run: |
        echo "Configuring server project (jsonserver)..."
        cd jsonserver
        qmake jsonserver.pro
        cd ..

        echo "Configuring client project (jsonclient)..."
        cd jsonclient
        qmake jsonclient.pro
        cd ..

    - name: Build Server
      run: |
        echo "Building server (jsonserver)..."
        cd jsonserver
        make -j$(nproc)
        mv jsonserver ../server_app
        cd ..

    - name: Build Client (Verbose)
      run: |
        echo "Building client (jsonclient)..."
        cd jsonclient
        # Используем V=1 для подробного вывода make
        make -j$(nproc) V=1 
        mv jsonclient ../client_app
        cd ..

    - name: Verify Executables
      run: |
        echo "Verifying compiled executables..."
        ls -l
        if [ -f server_app ]; then
          echo "Server application (server_app) found."
        else
          echo "Server application (server_app) NOT found!"
          exit 1
        fi
        if [ -f client_app ]; then
          echo "Client application (client_app) found."
        else
          echo "Client application (client_app) NOT found!"
          exit 1
        fi

    # - name: Run Basic Test (Optional)
    #   run: |
    #     echo "Attempting to run server and client..."
    #     ./server_app &
    #     SERVER_PID=$!
    #     sleep 2
    #     ./client_app "testuser" || true
    #     sleep 1
    #     kill $SERVER_PID || true
    #     echo "Server stopped."

    - name: Upload Build Artifacts (Optional)
      uses: actions/upload-artifact@v4
      with:
        name: Qt_Apps_Linux_Build
        path: |
          ./client_app
          ./server_app